variables:
  - group: qanda-webapp-dev

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadSecureFile@1
    displayName: 'Download disallow_all_robots.txt'
    name: disallowAllRobotsTxtFile
    inputs:
      secureFile: 'disallow_all_robots.txt'

  - script: tree $(Agent.TempDirectory)
    displayName: 'List downloaded files'

  - task: CopyFiles@2
    displayName: 'Move disallow_all_robots.txt to public directory'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'disallow_all_robots.txt'
      TargetFolder: 'public'

  - script: mv disallow_all_robots.txt robots.txt
    workingDirectory: 'public'
    displayName: 'Rename disallow_all_robots.txt to robots.txt'

  - script: tree .
    displayName: 'List project files'

  - task: AzureStaticWebApp@0
    displayName: 'Build and deploy to Azure Static Web App'
    inputs:
      output_location: 'dist'
    env:
      azure_static_web_apps_api_token: $(AzureSWADeploymentToken)
      VUE_APP_AAD_TENANT: $(VUE_APP_AAD_TENANT)
      VUE_APP_API_URL: $(VUE_APP_API_URL)
      VUE_APP_CLIENT_ID: $(VUE_APP_CLIENT_ID)
      VUE_APP_REDIRECT_URI: $(VUE_APP_REDIRECT_URI)
